// A4 PDF export for performance reviews, same 14 sections as docxBuilder.js.
// pdfkit is pure JS, so it's safe on App Engine Standard.

import PDFDocument from 'pdfkit'

// ── Page geometry (A4 points) ────────────────────────────────────────────────
const PW   = 595.28
const PH   = 841.89
const M    = 50          // margin
const CW   = PW - M * 2 // content width: 495.28
const BOT  = PH - M - 20 // bottom trigger (leave room for footer)

// ── Brand palette ────────────────────────────────────────────────────────────
const PURPLE = '#341272'
const GPURPLE = '#C4B5FD'
const GRAY   = '#6B7280'
const LIGHT  = '#F3F4F6'
const ALT    = '#FAFAFA'
const BGRID  = '#E5E7EB'
const BLACK  = '#111827'

// ── Helpers ──────────────────────────────────────────────────────────────────

function _checkPage(doc, y, need = 30) {
  if (y + need > BOT) { doc.addPage(); return M }
  return y
}

function _h1(doc, text, y) {
  y = _checkPage(doc, y, 34)
  doc.font('Helvetica-Bold').fontSize(12).fillColor(PURPLE).text(text, M, y, { width: CW })
  y += 16
  doc.moveTo(M, y).lineTo(M + CW, y).strokeColor(GPURPLE).lineWidth(0.5).stroke()
  return y + 8
}

function _h2(doc, text, y) {
  y = _checkPage(doc, y, 24)
  doc.font('Helvetica-Bold').fontSize(10).fillColor(PURPLE).text(text, M, y, { width: CW })
  return y + 16
}

function _para(doc, text, y) {
  const s = String(text ?? '').slice(0, 3000)
  const h = doc.font('Helvetica').fontSize(9).heightOfString(s, { width: CW }) + 4
  y = _checkPage(doc, y, h)
  doc.font('Helvetica').fontSize(9).fillColor(BLACK).text(s, M, y, { width: CW })
  return y + h + 4
}

// ── Table drawing ────────────────────────────────────────────────────────────
// headers: string[]
// rows:    (string | { v: string; bold?: boolean })[][]
// colWidths: number[] — must sum to CW (495.28)
function _table(doc, headers, rows, colWidths, startY) {
  const PAD = 4
  let y = _checkPage(doc, startY, 22)

  // Compute row height: pdfkit heightOfString uses current font settings
  function rowH(cells, bold) {
    let max = 18
    for (let i = 0; i < cells.length; i++) {
      const v = typeof cells[i] === 'object' ? cells[i].v : String(cells[i] ?? '')
      const h = doc.font(bold ? 'Helvetica-Bold' : 'Helvetica')
                    .fontSize(8).heightOfString(v, { width: colWidths[i] - PAD * 2 }) + PAD * 2
      if (h > max) max = h
    }
    return max
  }

  // Header row
  const hh = rowH(headers, true)
  y = _checkPage(doc, y, hh)
  doc.rect(M, y, CW, hh).fill(LIGHT)
  let x = M
  for (let i = 0; i < headers.length; i++) {
    doc.font('Helvetica-Bold').fontSize(8).fillColor(PURPLE)
       .text(String(headers[i]), x + PAD, y + PAD, { width: colWidths[i] - PAD * 2, lineBreak: false, ellipsis: true })
    x += colWidths[i]
  }
  doc.rect(M, y, CW, hh).stroke(BGRID)
  y += hh

  // Data rows
  for (let r = 0; r < rows.length; r++) {
    const row = rows[r]
    const isBoldRow = row._bold === true
    const rh = rowH(row, isBoldRow)
    y = _checkPage(doc, y, rh)

    doc.rect(M, y, CW, rh).fill(r % 2 === 0 ? ALT : '#FFFFFF')

    x = M
    for (let i = 0; i < row.length; i++) {
      const cell = row[i]
      const cellVal   = (typeof cell === 'object' && cell !== null && !Array.isArray(cell)) ? String(cell.v ?? '') : String(cell ?? '')
      const cellBold  = (typeof cell === 'object' && cell !== null) ? !!cell.bold : isBoldRow
      doc.font(cellBold ? 'Helvetica-Bold' : 'Helvetica')
         .fontSize(8).fillColor(BLACK)
         .text(cellVal, x + PAD, y + PAD, { width: colWidths[i] - PAD * 2 })
      x += colWidths[i]
    }
    doc.rect(M, y, CW, rh).stroke(BGRID)
    y += rh
  }

  return y + 8
}

// ── Cover page ───────────────────────────────────────────────────────────────
function _cover(doc, p) {
  const e = p.employee || {}
  const period = p.period || {}
  const mid = PH / 2 - 80

  doc.rect(M, mid - 20, CW, 6).fill(PURPLE)

  doc.font('Helvetica-Bold').fontSize(20).fillColor(PURPLE)
     .text('AI-Based Employee Performance Analysis', M, mid, { width: CW, align: 'center' })

  doc.font('Helvetica').fontSize(13).fillColor(GRAY)
     .text('FieldFlow', M, mid + 34, { width: CW, align: 'center' })

  if (e.name) {
    doc.font('Helvetica-Bold').fontSize(14).fillColor(BLACK)
       .text(e.name, M, mid + 66, { width: CW, align: 'center' })
  }
  if (period.label) {
    doc.font('Helvetica').fontSize(11).fillColor(GRAY)
       .text(period.label, M, mid + 86, { width: CW, align: 'center' })
  }

  doc.rect(M, mid + 106, CW, 6).fill(PURPLE)

  doc.font('Helvetica').fontSize(9).fillColor(GRAY)
     .text(`Generated by FieldFlow · ${new Date().toLocaleDateString('en-IN')}`, M, mid + 126, { width: CW, align: 'center' })
}

// ── Footers stamped on all pages after content is drawn (needs bufferPages) ──
function _stampFooters(doc, employeeName) {
  const range = doc.bufferedPageRange()
  for (let i = 0; i < range.count; i++) {
    doc.switchToPage(range.start + i)
    doc.font('Helvetica').fontSize(7).fillColor(GRAY)
       .text(`FieldFlow · ${employeeName || 'Performance Review'} · Confidential`,
             M, PH - 28, { width: CW * 0.7, lineBreak: false })
       .text(`Page ${i + 1} of ${range.count}`,
             M, PH - 28, { width: CW, align: 'right', lineBreak: false })
  }
}

// ── Section builders ─────────────────────────────────────────────────────────

function _sectionEmployee(doc, p, y) {
  const e = p.employee || {}
  const period = p.period || {}
  y = _h1(doc, '1. Employee Details', y)
  const rows = [
    ['Employee Name',    e.name    || '—'],
    ['Designation',      e.designation || '—'],
    ['Department',       e.department  || '—'],
    ['Review Period',    `${period.label || ''} (${period.start || ''} → ${period.end || ''})`],
    ['Reporting Manager',e.manager_name || '—'],
    ['Review Date',      new Date().toLocaleDateString('en-IN')],
  ]
  return _table(doc, ['Field', 'Details'], rows, [150, 345], y)
}

function _sectionActivityOverview(doc, p, y) {
  const ws = p.worker_stats
  if (!ws) return y
  const q = ws.quality || {}
  y = _h1(doc, '2. Activity Overview', y)
  const statsRows = [
    ['Total Reports',    String(ws.reportCount ?? 0)],
    ['Last 30 Days',     String(ws.recentCount ?? 0)],
    ['Total Beneficiaries', String(ws.totalBenef ?? 0)],
  ]
  y = _table(doc, ['Metric', 'Value'], statsRows, [300, 195], y)
  y = _h2(doc, 'Report Quality', y)
  const qualRows = [
    ['Description Quality', `${q.description ?? 0}%`],
    ['Beneficiary Data',    `${q.beneficiaries ?? 0}%`],
    ['Photo Attached',      `${q.photo ?? 0}%`],
    ['Location Tagged',     `${q.location ?? 0}%`],
    ['Overall Quality',     { v: `${q.overall ?? 0}%`, bold: true }],
  ]
  return _table(doc, ['Quality Metric', 'Percentage'], qualRows, [300, 195], y)
}

function _sectionAreaBreakdown(doc, p, y) {
  const ws = p.worker_stats
  if (!ws || !ws.areaBreakdown?.length) return y
  y = _h1(doc, '3. Area Breakdown', y)
  const totalReports = ws.areaBreakdown.reduce((s, r) => s + r.reports, 0)
  const totalBenef   = ws.areaBreakdown.reduce((s, r) => s + r.benef, 0)
  const rows = [
    ...ws.areaBreakdown.map(r => [
      r.area, String(r.reports), String(r.benef),
      `${r.photosPct ?? 0}%`, `${r.locatedPct ?? 0}%`,
    ]),
    [
      { v: 'Total', bold: true }, { v: String(totalReports), bold: true },
      { v: String(totalBenef), bold: true }, '', '',
    ],
  ]
  return _table(doc,
    ['Area', 'Reports', 'Beneficiaries', 'Photos %', 'Located %'],
    rows,
    [175, 65, 90, 85, 80],
    y)
}

function _sectionAiAnalysis(doc, p, y) {
  if (!p.ai_analysis) return y
  y = _h1(doc, '4. AI Analysis', y)
  const lines = String(p.ai_analysis).split('\n').filter(l => l.trim())
  for (const line of lines) {
    y = _para(doc, line.replace(/^#+\s*/, '').replace(/\*\*/g, ''), y)
  }
  return y
}

function _sectionScoringModel(doc, y) {
  y = _h1(doc, '5. AI Scoring Model', y)
  y = _para(doc, 'The AI analysis is based on 4 main factors:', y)
  const rows = [
    ['Performance KPIs',                     '40%'],
    ['Activity Completion',                  '30%'],
    ['Key Learning & Development',           '20%'],
    ['Discipline / Behaviour / Consistency', '10%'],
  ]
  y = _table(doc, ['Category', 'Weightage'], rows, [350, 145], y)
  y = _para(doc, 'Final AI Score = (Performance Score × 40%) + (Activity Score × 30%) + (Learning Score × 20%) + (Discipline Score × 10%)', y)
  return y
}

function _sectionSummary(doc, p, y) {
  const w = p.weighted || {}
  y = _h1(doc, '6. Overall AI Score Summary', y)
  const rows = [
    ['Performance KPIs',    `${w.kpi_score}%`,        '40%', (w.kpi_score * 0.4).toFixed(1)],
    ['Activity Completion', `${w.activity_score}%`,   '30%', (w.activity_score * 0.3).toFixed(1)],
    ['Key Learning',        `${w.learning_score}%`,   '20%', (w.learning_score * 0.2).toFixed(1)],
    ['Discipline',          `${w.discipline_score}%`, '10%', (w.discipline_score * 0.1).toFixed(1)],
    [
      { v: 'Final AI Score', bold: true }, '',
      '', { v: `${w.final} / 100`, bold: true },
    ],
  ]
  y = _table(doc, ['Category', 'Score %', 'Weight', 'Weighted'], rows, [195, 100, 100, 100], y)
  y = _checkPage(doc, y, 28)
  doc.font('Helvetica-Bold').fontSize(9).fillColor(BLACK)
     .text(`Final Rating: `, M, y, { continued: true })
     .font('Helvetica').text(w.rating || '—')
  y += 14
  doc.font('Helvetica-Bold').fontSize(9).fillColor(BLACK)
     .text(`AI Recommendation: `, M, y, { continued: true })
     .font('Helvetica').text(p.recommendation || '—', { width: CW - 130 })
  return y + 20
}

function _sectionKpis(doc, p, y) {
  y = _h1(doc, '7. Performance KPI Review', y)
  const rows = (p.kpis || []).map(k => [
    k.area,
    typeof k.score === 'number' ? k.score.toFixed(1) : String(k.score ?? '—'),
    k.observation || '—',
  ])
  return _table(doc, ['Performance Area', 'Score / 5', 'AI Observation'], rows, [150, 65, 280], y)
}

function _sectionActivities(doc, p, y) {
  y = _h1(doc, '8. Activity-Based Review', y)
  const rows = (p.activities || []).map(a => [
    a.name,
    String(a.target ?? ''),
    String(a.completed ?? ''),
    `${a.completion_pct ?? 0}%`,
    typeof a.quality === 'number' ? a.quality.toFixed(1) : String(a.quality ?? '—'),
    a.remark || '—',
  ])
  return _table(doc,
    ['Activity', 'Target', 'Done', '%', 'Quality', 'Remark'],
    rows,
    [130, 45, 45, 45, 55, 175],
    y)
}

function _sectionLearning(doc, p, y) {
  y = _h1(doc, '9. Key Learning Review', y)
  const rows = (p.learning || []).map(l => [
    l.area,
    typeof l.score === 'number' ? l.score.toFixed(1) : String(l.score ?? '—'),
    l.observation || '—',
  ])
  y = _table(doc, ['Learning Area', 'Score / 5', 'AI Analysis'], rows, [150, 65, 280], y)
  if (p.learning_insight) {
    doc.font('Helvetica-Bold').fontSize(9).fillColor(BLACK)
       .text('AI Learning Insight: ', M, y, { continued: true })
       .font('Helvetica').text(p.learning_insight, { width: CW - 110 })
    y += 20
  }
  return y
}

function _sectionTrend(doc, p, y) {
  y = _h1(doc, '10. Monthly Performance Trend', y)
  const rows = (p.trend || []).map(t => [t.month, `${t.score}%`])
  return _table(doc, ['Month', 'Performance %'], rows, [248, 247], y)
}

function _sectionAnalysis(doc, p, y) {
  const w = p.weighted || {}
  y = _h1(doc, '11. AI-Generated Performance Analysis', y)
  y = _h2(doc, 'Overall Analysis', y)
  y = _para(doc, p.overall_analysis || `Final score ${w.final} places this employee in the ${w.rating} band.`, y)

  y = _h2(doc, 'Strength Areas', y)
  const strengthRows = (p.strengths || []).map(s => [s.area, s.reason || '—'])
  y = _table(doc, ['Strength Area', 'Reason'], strengthRows, [150, 345], y)

  y = _h2(doc, 'Improvement Areas', y)
  const impRows = (p.improvements || []).map(s => [s.area, s.reason || '—'])
  y = _table(doc, ['Improvement Area', 'AI Reason'], impRows, [150, 345], y)

  return y
}

function _sectionRisk(doc, p, y) {
  const r = p.risk || {}
  const n = p.risk_notes || {}
  y = _h1(doc, '12. AI Risk & Potential Analysis', y)
  const rows = [
    ['Performance Risk',    r.performance   || '—', n.performance   || '—'],
    ['Growth Potential',    r.growth        || '—', n.growth        || '—'],
    ['Promotion Readiness', r.promotion     || '—', n.promotion     || '—'],
    ['Training Need',       r.training_need || '—', n.training_need || '—'],
    ['Retention Value',     r.retention     || '—', n.retention     || '—'],
  ]
  return _table(doc, ['Parameter', 'Status', 'AI Interpretation'], rows, [140, 100, 255], y)
}

function _sectionRecommendation(doc, p, y) {
  y = _h1(doc, '13. Final AI Recommendation', y)
  y = _h2(doc, 'Recommendation', y)
  y = _para(doc, p.recommendation || '—', y)
  y = _h2(doc, 'Suggested Action Plan', y)
  const rows = (p.action_plan || []).map(a => [
    a.action, `${a.timeline_days || 0} days`, a.expected_result || '—',
  ])
  return _table(doc, ['Action', 'Timeline', 'Expected Result'], rows, [180, 70, 245], y)
}

function _sectionRatingScale(doc, p, y) {
  const w = p.weighted || {}
  y = _h1(doc, '14. Final Rating Scale', y)
  const scaleRows = [
    ['90–100',   'Excellent',         'Promotion / high increment'],
    ['80–89',    'Good',              'Continue / increment recommended'],
    ['70–79',    'Satisfactory',      'Training required'],
    ['60–69',    'Needs Improvement', 'Improvement plan required'],
    ['Below 60', 'Poor',              'Performance improvement plan'],
  ]
  y = _table(doc, ['Score', 'Rating', 'Decision'], scaleRows, [100, 130, 265], y)
  y = _checkPage(doc, y, 42)
  doc.font('Helvetica-Bold').fontSize(9).fillColor(BLACK)
     .text('Current Employee Final Score: ', M, y, { continued: true })
     .font('Helvetica').text(`${w.final} / 100`)
  y += 14
  doc.font('Helvetica-Bold').fontSize(9).fillColor(BLACK)
     .text('Final Rating: ', M, y, { continued: true })
     .font('Helvetica').text(w.rating || '—')
  y += 14
  doc.font('Helvetica-Bold').fontSize(9).fillColor(BLACK)
     .text('Final Decision: ', M, y, { continued: true })
     .font('Helvetica').text(p.final_decision || '—')
  return y + 14
}

// ── Public API ───────────────────────────────────────────────────────────────

/** Build the review PDF; payload has the same shape buildReviewDocx receives. */
export async function buildReviewPdf(payload) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: M, autoFirstPage: true, bufferPages: true })
    const chunks = []
    doc.on('data', c => chunks.push(c))
    doc.on('end',  () => resolve(Buffer.concat(chunks)))
    doc.on('error', reject)

    const empName = payload?.employee?.name || 'Review'

    // ── Cover page ──────────────────────────────────────────────────────────
    _cover(doc, payload)
    doc.addPage()

    // ── Sections ────────────────────────────────────────────────────────────
    let y = M
    y = _sectionEmployee(doc, payload, y)
    y = _sectionActivityOverview(doc, payload, y)
    y = _sectionAreaBreakdown(doc, payload, y)
    y = _sectionAiAnalysis(doc, payload, y)
    y = _sectionScoringModel(doc, y)
    y = _sectionSummary(doc, payload, y)
    y = _sectionKpis(doc, payload, y)
    y = _sectionActivities(doc, payload, y)
    y = _sectionLearning(doc, payload, y)
    y = _sectionTrend(doc, payload, y)
    y = _sectionAnalysis(doc, payload, y)
    y = _sectionRisk(doc, payload, y)
    y = _sectionRecommendation(doc, payload, y)
    _sectionRatingScale(doc, payload, y)

    // ── Footers on every page (stamped after all content) ───────────────────
    _stampFooters(doc, empName)

    doc.end()
  })
}
